################################# Default configuration ###################
baseURL = "https://assomyharmony.org/"
title = "My Harmony | Astreintes de 18 h à 9 heures"
theme = "harmony"

googleAnalytics = "UA-123-45"

# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo-mh.jpg"
# Meta data
description = ""
author = "Netary"
# Contact Information
mobile = "0124857985320"
email = "demo@email.com"
# contact form action
contact_form_action = "/merci" # contact form works with : https://formspree.io
# Google Analitycs

multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 My Harmony Tous droits réservés"


######################### english navigation #############################
# main menu
[[Languages.en.menu.main]]
name = "Accueil"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "L’association"
URL = "/about"
weight = 2

[[Languages.en.menu.main]]
name = "Précarité Menstruelle"
URL = "/service"
weight = 4

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

[[Languages.en.menu.main]]
name = "Nous Contacter"
URL = "/contact"
weight = 7


# footer menu
[[Languages.en.menu.footer]]
name = "L'association"
URL = "about"
weight = 1

[[Languages.en.menu.footer]]
name = "Précarité Menstruelle"
URL = "service"
weight = 3

[[Languages.en.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
# copyright
copyright = "Copyright &copy; 2020 [Themefisher](https://themefisher.com) All Rights Reserved"


######################### france navigation #############################
# main menu
[[Languages.fr.menu.main]]
name = "Accueil"
URL = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "À propos"
URL = "about"
weight = 2

[[Languages.fr.menu.main]]
name = "Projet"
URL = "project"
weight = 3

[[Languages.fr.menu.main]]
name = "Un service"
URL = "service"
weight = 4

[[Languages.fr.menu.main]]
name = "Blog"
URL = "blog"
weight = 5

[[Languages.fr.menu.main]]
weight = 6
name = "Pages"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "FAQ"
  URL = "faq"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Tarification"
  URL = "pricing"

[[Languages.fr.menu.main]]
name = "Contact"
URL = "contact"
weight = 7


# footer menu
[[Languages.fr.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[Languages.fr.menu.footer]]
name = "Project"
URL = "project"
weight = 2

[[Languages.fr.menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[Languages.fr.menu.footer]]
name = "Pricing"
URL = "pricing"
weight = 4

[[Languages.fr.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[Languages.fr.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6
